name: Build & Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Run Linter
        run: flake8 app

      - name: Run Tests
        run: pytest tests

      - name: Build Docker Image (CI only)
        run: docker build -t groq-quotes .
